# Generated by Django 3.0 on 2020-06-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='inghetata',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
